variables:
  S3_BUCKET_DEV: origin.dev.ebi.emblstatic.net
  S3_BUCKET_PROD: origin.ebi.emblstatic.net
# do not define here, put in project variables
  AWS_KEY: key
  AWS_SECRET: secret-key
  
stages:
  - deploy
  
deploy_aws_dev:
  image: ebiwd/alpine-ssh
  stage: deploy
  tags:
    - docker
  before_script:
    - add-aws-key ${AWS_KEY} ${AWS_SECRET}
  script: 
    - bin/deploy-aws
  only: 
    - v1.2
  except:
    - /-code$/

deploy_aws_live:
  image: ebiwd/alpine-ssh
  stage: deploy
  tags:
    - docker
  before_script:
    - add-aws-key ${AWS_KEY} ${AWS_SECRET}
  script: 
    - bin/deploy-aws prod
  only: 
    - tags
